name: Publish on PyPI and Docker Hub
on:
  release:
    types: [published]
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # pypi:
  #   name: Publish on PyPI
  #   runs-on: ubuntu-latest
  #   permissions:
  #     # IMPORTANT: this permission is mandatory for trusted publishing
  #     id-token: write
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v3

  #     - name: Set up the environment
  #       uses: ./.github/actions/setup-poetry-env

  #     - name: Export tag
  #       id: vars
  #       run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

  #     - name: Build source files
  #       run: |
  #         source .venv/bin/activate
  #         poetry version $RELEASE_VERSION
  #         poetry build
  #       env:
  #         RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

  #     - name: Publish package distributions to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1

  #     - name: Build Changelog
  #       id: github_release
  #       uses: mikepenz/release-changelog-builder-action@v3
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    # needs: publish
    name: Publish on Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: "‚òÅÔ∏è checkout repository"
        uses: actions/checkout@v3

      # - name: "üîß setup buildx"
      #   uses: docker/setup-buildx-action@v1

      # - name: "üîß cache docker layers"
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: "geoluminate"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "geoluminate/geoluminate"
          tags: latest



      - name: "üì¶ docker build"
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # outputs: type=docker,dest=/tmp/docker.tar
          # cache-from: type=gha, scope=${{ github.workflow }}
          # cache-to: type=gha, scope=${{ github.workflow }}

      # - name: "üìÇ docker artifacts"
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: docker
      #     path: /tmp/docker.tar